apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    command: ["while true; do date; sleep $TIME_FREQ;done"]
    env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
    volumeMounts:
    - mountPath: /opt/time
      name: mydir
    - mountPath: /opt/time/time-check.log
      name: myfile
    resources: {}

   volumes:
    - name: mydir
      hostPath:
        # Ensure the file directory is created.
        path: /opt/time
        type: DirectoryOrCreate
    - name: myfile
                                                                    1,1           Top