apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-16T06:20:57Z"
  labels:
    run: dvl1987
  name: dvl1987
  namespace: default
  uid: d6734891-55d6-4bb2-903f-56415064ca4a
spec:
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c","while true; do date; sleep $TIME_FREQ;done>/opt/time/time-check.log"]
    env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ

    imagePullPolicy: Always
    name: time-check
    resources: {}

    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-s6kl4
      readOnly: true

  volumes:
  - name: mydir
    hostPath:
      path: /opt/time
      type: DirectoryOrCreate
  