apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-claim
  containers:
  - image: nginx:alpine
    name: logger
    resources: {}
    volumeMounts:
        - mountPath: "/var/www/nginx"
          name: log-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}